"""initial research store schema

Revision ID: f3bb75c2004c
Revises: 
Create Date: 2026-08-07 23:58:46.414226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bb75c2004c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recruitment_channel', sa.Enum('dev_community', 'college', 'ngo', 'professional', 'other', name='recruitmentchannel'), nullable=False),
    sa.Column('consent_version', sa.String(), nullable=False),
    sa.Column('consent_research', sa.Boolean(), nullable=False),
    sa.Column('consent_open_data', sa.Boolean(), nullable=False),
    sa.Column('age_band', sa.Enum('age_18_24', 'age_25_34', 'age_35_44', 'age_45_54', 'age_55_plus', name='ageband'), nullable=True),
    sa.Column('education_band', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('work_status', sa.Enum('student', 'employed', 'self_employed', 'not_working', 'prefer_not_to_say', name='workstatus'), nullable=True),
    sa.Column('withdrawn', sa.Boolean(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('participant_code')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('condition', sa.Enum('honest_untimed', 'honest_timed', 'fake_timed', 'fake_untimed', name='condition'), nullable=False),
    sa.Column('module_order', sa.JSON(), nullable=False),
    sa.Column('device_type', sa.Enum('mobile', 'tablet', 'desktop', name='devicetype'), nullable=True),
    sa.Column('input_method', sa.Enum('touch', 'mouse_keyboard', name='inputmethod'), nullable=True),
    sa.Column('viewport_width', sa.Integer(), nullable=True),
    sa.Column('user_agent_family', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('abandoned_at_module', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['participant_code'], ['participants.participant_code'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('quality_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('flag_type', sa.Enum('attention_check_failed', 'straight_lining', 'latency_floor', 'excessive_timeouts', 'duplicate_suspected', name='flagtype'), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_baseline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('sentence_id', sa.String(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('read_time_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('response_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('module_code', sa.Enum('M1', 'M2', 'M3', 'M4', 'M5', name='modulecode'), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('item_bank_version', sa.String(), nullable=False),
    sa.Column('position_in_module', sa.Integer(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('focus_lost', sa.Boolean(), nullable=False),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('reading_baseline')
    op.drop_table('quality_flags')
    op.drop_table('sessions')
    op.drop_table('participants')
    # ### end Alembic commands ###
